language:
  - php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

services:
    - elasticsearch
    - redis-server

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer install
    - sudo curl -O 'http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-precise-amd64.deb'
    - sudo dpkg -i ./wkhtmltox-0.12.2.1_linux-precise-amd64.deb

script:
    - phpunit

notifications:
    email: "info@endroid.nl"
