application:
    image: endroid/docker-application
    volumes:
        - .:/var/www/html
    tty: true
php:
    build: docker/php/
    volumes:
        - ~/.ssh:/root/.ssh
    volumes_from:
        - application
    links:
        - mysql
    expose:
        - 9000:9000
mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony_demo
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - 3306:3306
nginx:
    build: docker/nginx/
    volumes_from:
        - application
    links:
        - php
    ports:
        - 80:80
grunt:
    image: endroid/docker-grunt
    volumes_from:
        - application
    tty: true