knp_snappy:
    pdf:
        enabled: true
        binary: %wkhtmltopdf_binary%
        options:
            - { name: dpi, value: 150 }
            - { name: lowquality, value: false }
            - { name: disable-smart-shrinking, value: true }
            - { name: margin-top, value: 0 }
            - { name: margin-right, value: 0 }
            - { name: margin-bottom, value: 0 }
            - { name: margin-left, value: 0 }
