app:
    resource: "@AppBundle/Controller/"
    type: annotation

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api-doc

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin